// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: item_images.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createItemImage = `-- name: CreateItemImage :one
INSERT INTO item_images(
    item_id,image_url
)
VALUES ($1,$2)
RETURNING id, item_id, image_url
`

type CreateItemImageParams struct {
	ItemID   sql.NullInt32 `json:"item_id"`
	ImageUrl string        `json:"image_url"`
}

func (q *Queries) CreateItemImage(ctx context.Context, arg CreateItemImageParams) (ItemImage, error) {
	row := q.db.QueryRowContext(ctx, createItemImage, arg.ItemID, arg.ImageUrl)
	var i ItemImage
	err := row.Scan(&i.ID, &i.ItemID, &i.ImageUrl)
	return i, err
}

const deleteItemImage = `-- name: DeleteItemImage :one
DELETE FROm item_images WHERE id = $1 
RETURNING id, item_id, image_url
`

func (q *Queries) DeleteItemImage(ctx context.Context, id int32) (ItemImage, error) {
	row := q.db.QueryRowContext(ctx, deleteItemImage, id)
	var i ItemImage
	err := row.Scan(&i.ID, &i.ItemID, &i.ImageUrl)
	return i, err
}

const updateItemImageURL = `-- name: UpdateItemImageURL :one
UPDATE item_images
SET
    image_url = $1
WHERE id = $2
RETURNING id, item_id, image_url
`

type UpdateItemImageURLParams struct {
	ImageUrl string `json:"image_url"`
	ID       int32  `json:"id"`
}

func (q *Queries) UpdateItemImageURL(ctx context.Context, arg UpdateItemImageURLParams) (ItemImage, error) {
	row := q.db.QueryRowContext(ctx, updateItemImageURL, arg.ImageUrl, arg.ID)
	var i ItemImage
	err := row.Scan(&i.ID, &i.ItemID, &i.ImageUrl)
	return i, err
}
