// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	FullName     string `json:"full_name"`
	CountryCode  string `json:"country_code"`
	City         string `json:"city"`
	Street       string `json:"street"`
	Landmark     string `json:"landmark"`
	MobileNumber int64  `json:"mobile_number"`
}

type Cart struct {
	Username   string `json:"username"`
	ID         int32  `json:"id"`
	TotalValue int32  `json:"total_value"`
}

type CartItem struct {
	CartID   int32         `json:"cart_id"`
	ItemID   int32         `json:"item_id"`
	Quantity sql.NullInt32 `json:"quantity"`
}

type Item struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Price     string    `json:"price"`
	CreatedBy string    `json:"created_by"`
	Discount  int32     `json:"discount"`
	Category  string    `json:"category"`
	CreatedAt time.Time `json:"created_at"`
}

type ItemImage struct {
	ID       int32  `json:"id"`
	ItemID   int32  `json:"item_id"`
	ImageUrl string `json:"image_url"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiredAt    time.Time `json:"expired_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	Username          string        `json:"username"`
	HashedPassword    string        `json:"hashed_password"`
	FullName          string        `json:"full_name"`
	MobileNumber      sql.NullInt64 `json:"mobile_number"`
	PasswordChangedAt time.Time     `json:"password_changed_at"`
	IsEmailVerified   bool          `json:"is_email_verified"`
	CreatedAt         time.Time     `json:"created_at"`
}
